# Generated by Django 3.2.7 on 2021-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_year', models.IntegerField(max_length=4)),
                ('project_class', models.CharField(choices=[('BE', 'Final Year'), ('TE', 'Third Year'), ('SE', 'Seconf Year')], default='BE', max_length=2)),
                ('project_members', models.CharField(max_length=300)),
                ('project_title', models.CharField(max_length=300)),
                ('project_mentor', models.CharField(max_length=300)),
                ('project_abstract', models.CharField(max_length=1000)),
                ('project_publication', models.CharField(max_length=300)),
            ],
        ),
    ]
