# Generated by Django 3.2.7 on 2021-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_year',
            field=models.IntegerField(),
        ),
    ]
