# Generated by Django 3.2.7 on 2021-09-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_projectmodel_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_class',
            field=models.CharField(choices=[('BE', 'BE'), ('TE', 'TE'), ('SE', 'SE')], default='BE', max_length=2),
        ),
    ]
