# Generated by Django 3.2.7 on 2021-09-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_projectmodel_project_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_year',
            field=models.IntegerField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2021'),
        ),
    ]
