# Generated by Django 3.2.7 on 2021-09-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_projectmodel_project_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_abstract',
            new_name='project_Abstract',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_class',
            new_name='project_Class',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_members',
            new_name='project_Members',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_mentor',
            new_name='project_Mentor',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_publication',
            new_name='project_Publication',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_title',
            new_name='project_Title',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='project_year',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_Year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2021),
        ),
    ]
