# Generated by Django 3.2.7 on 2021-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20210909_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_Domain',
            field=models.CharField(default='Big Data Analytics and Machine Learning', max_length=300),
        ),
    ]
