# Generated by Django 3.2.7 on 2021-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_projectmodel_project_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_Abstract',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_Members',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_Mentor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_Title',
            field=models.CharField(max_length=500),
        ),
    ]
