# Generated by Django 3.2.7 on 2021-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20210909_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_Video',
            field=models.CharField(default='', max_length=400),
        ),
    ]
